import groovy.json.JsonSlurper
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "app.risuko.webview_upgrade"
    compileSdk = 36

    defaultConfig {
        minSdk = 24
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    sourceSets["main"].kotlin.srcDir(
        layout.buildDirectory.dir("generated/source/webview-upgrade")
    )
}

dependencies {
    implementation(project(":tauri-android"))
}

val defaultMinUpgradeMajor = 106
val defaultMinSupportedMajor = 75

@Suppress("UNCHECKED_CAST")
fun parsePluginBlock(block: Map<String, Any?>?): Pair<Int, Int> {
    if (block == null) return defaultMinUpgradeMajor to defaultMinSupportedMajor
    val upgrade = (block["minUpgradeMajor"] as? Number)?.toInt() ?: defaultMinUpgradeMajor
    val supported = (block["minSupportedMajor"] as? Number)?.toInt() ?: defaultMinSupportedMajor
    require(upgrade > 0) { "minUpgradeMajor must be > 0, got $upgrade" }
    require(supported > 0) { "minSupportedMajor must be > 0, got $supported" }
    require(supported <= upgrade) { "minSupportedMajor ($supported) must be <= minUpgradeMajor ($upgrade)" }
    return upgrade to supported
}

@Suppress("UNCHECKED_CAST")
fun readFromEnv(jsonText: String?): Pair<Int, Int>? {
    if (jsonText.isNullOrBlank()) return null
    val parsed = try {
        JsonSlurper().parseText(jsonText) as? Map<String, Any?>
    } catch (e: Exception) {
        logger.warn("TAURI_WEBVIEW_UPGRADE_PLUGIN_CONFIG parse error: ${e.message}; using defaults")
        null
    } ?: return null
    return parsePluginBlock(parsed)
}

@Suppress("UNCHECKED_CAST")
fun readFromTauriConf(file: File): Pair<Int, Int>? {
    val root = JsonSlurper().parse(file) as? Map<String, Any?> ?: return null
    val plugins = root["plugins"] as? Map<String, Any?> ?: return null
    val block = plugins["webview-upgrade"] as? Map<String, Any?> ?: return null
    return parsePluginBlock(block)
}

fun findTauriConf(start: File): File? {
    var current: File? = start
    while (current != null) {
        val candidate = File(current, "tauri.conf.json")
        if (candidate.exists()) return candidate
        current = current.parentFile
    }
    return null
}

val generatedConfigDir = layout.buildDirectory.dir("generated/source/webview-upgrade")

val generateWebViewUpgradeConfig = tasks.register("generateWebViewUpgradeConfig") {
    val envJson = System.getenv("TAURI_WEBVIEW_UPGRADE_PLUGIN_CONFIG")
    val tauriConfFile = findTauriConf(projectDir)
    if (envJson.isNullOrBlank() && tauriConfFile != null) {
        inputs.file(tauriConfFile)
    }
    inputs.property("envJson", envJson ?: "")
    outputs.dir(generatedConfigDir)

    doLast {
        val (minUpgrade, minSupported, source) = when {
            !envJson.isNullOrBlank() ->
                readFromEnv(envJson)?.let { Triple(it.first, it.second, "TAURI_WEBVIEW_UPGRADE_PLUGIN_CONFIG env var") }
                    ?: Triple(defaultMinUpgradeMajor, defaultMinSupportedMajor, "defaults (env var unparseable)")
            tauriConfFile != null ->
                readFromTauriConf(tauriConfFile)?.let { Triple(it.first, it.second, "tauri.conf.json") }
                    ?: Triple(defaultMinUpgradeMajor, defaultMinSupportedMajor, "defaults (tauri.conf.json had no block)")
            else -> Triple(defaultMinUpgradeMajor, defaultMinSupportedMajor, "defaults (no config found)")
        }
        val outDir = generatedConfigDir.get().asFile
        val pkgDir = File(outDir, "app/risuko/webview_upgrade")
        pkgDir.mkdirs()
        File(pkgDir, "WebViewUpgradeConfig.kt").writeText(
            """
            // Generated by build.gradle.kts at build time. Do not edit by hand.
            // Source: $source
            package app.risuko.webview_upgrade

            internal object WebViewUpgradeConfig {
                const val MIN_UPGRADE_MAJOR: Int = $minUpgrade
                const val MIN_SUPPORTED_MAJOR: Int = $minSupported
            }
            """.trimIndent() + "\n"
        )
        logger.lifecycle(
            "WebViewUpgradeConfig: minUpgradeMajor=$minUpgrade, minSupportedMajor=$minSupported (from $source)"
        )
    }
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(generateWebViewUpgradeConfig)
}
